# Generated by Django 5.0.6 on 2024-07-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Student_Id', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Course', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Location', models.CharField(max_length=200)),
                ('Phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
