# Generated by Django 5.0.6 on 2024-07-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='Student_Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
